services:
  php:
    build:
      context: ..
      dockerfile: contrib/Dockerfile
    container_name: yii2-php
    volumes:
      - ../:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mariadb:11
    container_name: yii2-mariadb
    environment:
      MYSQL_DATABASE: yii2app
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mariadb_data: